### ISSUE TITLE
Proposal: Acute and Chronic Training Load (ATL/CTL) in activity's extended data

### ISSUE THREAD

**Issue by erikvankempen** [thomaschampagne/elevate#193]
Both ATL and CTL are part of performance management, as used by some commercial tools. Both the ATL and CTL are measures of performance with a different approach.
### ATL (fatigue)

An exponentially weighted average of the TRIMP of activitities in the last 7 days is a measure of fatigue.
### CTL (fitness)

An exponentially weighted average of the TRIMP of activitities in the last 42 days is a measure of fitness. CTL is used by a lot of athletes to gauge their current level of fitness. They try to peak their CTL on the day of a race.

The difference between both values on a specific day is called Training Stress Balance (TSB) and is a measure for performance on that specific day.

Calculation could be based on the formulas from http://fellrnr.com/wiki/Modeling_Human_Performance#The_TSB_Formulas.

![image](https://cloud.githubusercontent.com/assets/5059510/12867760/a39ae388-ccf6-11e5-85f7-dc45f3de233f.png)
### Current status

Currently I am working on implementing this feature, but I am a bit stuck with gathering TRIMP values from previous activitities.

**Comment by thomaschampagne** [comment]
@erikvankempen Perfect :)

**Comment by thomaschampagne** [comment]
https://drive.google.com/open?id=0B4AhWY3qWuORa2gwQzhVcEZ1V1U

**Comment by thomaschampagne** [comment]
@erikvankempen i will dive into the process which fetch all activities and stream and do calculation in. Because this will be used for my features i planned and this one.

**Comment by erikvankempen** [comment]
@thomaschampagne cool. If you need any help, just notify me.

**Comment by thomaschampagne** [comment]
**Tasks**
*Synchronization*
- [ ] Ensure activities unicity while synchronize
- [ ] Do not re-save Computed activities if no new activities found
- [ ] Remove zones from sync: add parameter 'noZones' in Activity computer => reduce size stored
- [ ] clean up outputFields: remove fields, rename to less long keys => reduce size stored
- [ ] Auto sync on strava.com only if a previous sync exist and older than 12h.

*Fitness trend*
- [ ] Display current CTL, ATL & TSB on graph screen

* TO THINK*
- [ ] Allow force sync?
- [ ] Clear current sync cache. Where put action?
